version: 1
genesis:
  app_state:
    staking:
      params:
        bond_denom: "gtn"
accounts:
- name: bob
  coins:
  - 10000gtn
- name: alice
  coins:
  - 5000000000gtn
  mnemonic: cargo ramp supreme review change various throw air figure humble soft steel slam pole betray inhale already dentist enough away office apple sample glue
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 1000000000gtn
- name: bomb
  bonded: 1000gtn
